// Vocabulary Database - SAT/GRE Level Words
const VOCABULARY = [
  { word: "aberration", definition: "A departure from what is normal or expected", partOfSpeech: "noun", example: "The warm December weather was an aberration from the usual freezing temperatures." },
  { word: "abhor", definition: "To regard with disgust and hatred", partOfSpeech: "verb", example: "She abhors violence of any kind." },
  { word: "abstruse", definition: "Difficult to understand; obscure", partOfSpeech: "adjective", example: "The professor's abstruse lecture left most students confused." },
  { word: "accolade", definition: "An award or privilege granted as a special honor", partOfSpeech: "noun", example: "The film received numerous accolades at the festival." },
  { word: "acrimony", definition: "Bitterness or ill feeling", partOfSpeech: "noun", example: "The divorce proceedings were filled with acrimony." },
  { word: "admonish", definition: "To warn or reprimand someone firmly", partOfSpeech: "verb", example: "The teacher admonished the students for talking during the exam." },
  { word: "adroit", definition: "Clever or skillful in using the hands or mind", partOfSpeech: "adjective", example: "The adroit negotiator quickly resolved the dispute." },
  { word: "adversity", definition: "Difficulties or misfortune", partOfSpeech: "noun", example: "She showed remarkable courage in the face of adversity." },
  { word: "aesthetic", definition: "Concerned with beauty or the appreciation of beauty", partOfSpeech: "adjective", example: "The building's aesthetic appeal made it a tourist attraction." },
  { word: "affable", definition: "Friendly, good-natured, or easy to talk to", partOfSpeech: "adjective", example: "The affable host made everyone feel welcome." },
  { word: "alacrity", definition: "Brisk and cheerful readiness", partOfSpeech: "noun", example: "She accepted the invitation with alacrity." },
  { word: "ambiguous", definition: "Open to more than one interpretation; unclear", partOfSpeech: "adjective", example: "The contract contained ambiguous language that led to disputes." },
  { word: "ameliorate", definition: "To make something bad or unsatisfactory better", partOfSpeech: "verb", example: "The new policies helped ameliorate working conditions." },
  { word: "anachronism", definition: "Something belonging to a different time period", partOfSpeech: "noun", example: "The medieval castle had a television, an obvious anachronism." },
  { word: "analogous", definition: "Comparable in certain respects", partOfSpeech: "adjective", example: "The human heart is analogous to a pump." },
  { word: "anathema", definition: "Something or someone that one vehemently dislikes", partOfSpeech: "noun", example: "Violence was anathema to his peaceful nature." },
  { word: "anomaly", definition: "Something that deviates from what is standard or expected", partOfSpeech: "noun", example: "The scientist investigated the anomaly in the data." },
  { word: "antipathy", definition: "A deep-seated feeling of dislike", partOfSpeech: "noun", example: "There was a strong antipathy between the two rival teams." },
  { word: "apathy", definition: "Lack of interest, enthusiasm, or concern", partOfSpeech: "noun", example: "Voter apathy led to low turnout in the election." },
  { word: "appease", definition: "To pacify or placate someone by giving in to demands", partOfSpeech: "verb", example: "They tried to appease the angry customers with refunds." },
  { word: "arbitrary", definition: "Based on random choice rather than reason", partOfSpeech: "adjective", example: "The rules seemed completely arbitrary and unfair." },
  { word: "arcane", definition: "Understood by few; mysterious or secret", partOfSpeech: "adjective", example: "The arcane rituals were known only to initiates." },
  { word: "arduous", definition: "Involving or requiring strenuous effort", partOfSpeech: "adjective", example: "The arduous climb took them three days." },
  { word: "articulate", definition: "Expressing oneself clearly and effectively", partOfSpeech: "adjective", example: "The articulate speaker captivated the audience." },
  { word: "ascetic", definition: "Characterized by severe self-discipline and abstention", partOfSpeech: "adjective", example: "The monk lived an ascetic lifestyle in the mountains." },
  { word: "assiduous", definition: "Showing great care and perseverance", partOfSpeech: "adjective", example: "Her assiduous attention to detail impressed her supervisors." },
  { word: "astute", definition: "Having an ability to accurately assess situations", partOfSpeech: "adjective", example: "The astute investor recognized the opportunity early." },
  { word: "audacious", definition: "Showing a willingness to take bold risks", partOfSpeech: "adjective", example: "The audacious rescue mission saved all the hostages." },
  { word: "auspicious", definition: "Conducive to success; favorable", partOfSpeech: "adjective", example: "The sunny weather was an auspicious start to the wedding." },
  { word: "austere", definition: "Severe or strict in manner; having no comforts", partOfSpeech: "adjective", example: "The prison cells were austere and cold." },
  { word: "avarice", definition: "Extreme greed for wealth or material gain", partOfSpeech: "noun", example: "His avarice eventually led to his downfall." },
  { word: "banal", definition: "So lacking in originality as to be obvious and boring", partOfSpeech: "adjective", example: "The speech was filled with banal platitudes." },
  { word: "belligerent", definition: "Hostile and aggressive", partOfSpeech: "adjective", example: "The belligerent customer was asked to leave the store." },
  { word: "benevolent", definition: "Well meaning and kindly", partOfSpeech: "adjective", example: "The benevolent donor gave millions to charity." },
  { word: "berate", definition: "To scold or criticize someone angrily", partOfSpeech: "verb", example: "The coach berated the team for their poor performance." },
  { word: "bombastic", definition: "High-sounding but with little meaning", partOfSpeech: "adjective", example: "His bombastic speeches impressed no one." },
  { word: "boorish", definition: "Rough and bad-mannered; coarse", partOfSpeech: "adjective", example: "His boorish behavior at dinner embarrassed everyone." },
  { word: "brevity", definition: "Concise and exact use of words", partOfSpeech: "noun", example: "The brevity of his response surprised everyone." },
  { word: "burgeon", definition: "To begin to grow or increase rapidly", partOfSpeech: "verb", example: "The tech industry continues to burgeon." },
  { word: "cacophony", definition: "A harsh, discordant mixture of sounds", partOfSpeech: "noun", example: "The cacophony of car horns filled the street." },
  { word: "cajole", definition: "To persuade someone to do something by flattery", partOfSpeech: "verb", example: "She cajoled him into helping with the project." },
  { word: "callous", definition: "Showing an insensitive disregard for others", partOfSpeech: "adjective", example: "His callous remarks hurt her deeply." },
  { word: "candor", definition: "The quality of being open and honest", partOfSpeech: "noun", example: "She appreciated his candor about the situation." },
  { word: "capricious", definition: "Given to sudden changes of mood or behavior", partOfSpeech: "adjective", example: "The capricious weather made planning difficult." },
  { word: "castigate", definition: "To reprimand someone severely", partOfSpeech: "verb", example: "The media castigated the politician for lying." },
  { word: "catalyst", definition: "A person or thing that precipitates an event", partOfSpeech: "noun", example: "The protest served as a catalyst for change." },
  { word: "caustic", definition: "Sarcastic in a scathing and bitter way", partOfSpeech: "adjective", example: "Her caustic wit could be intimidating." },
  { word: "charlatan", definition: "A person falsely claiming to have special knowledge", partOfSpeech: "noun", example: "The supposed psychic was exposed as a charlatan." },
  { word: "circumspect", definition: "Wary and unwilling to take risks", partOfSpeech: "adjective", example: "He was circumspect about sharing personal information." },
  { word: "clandestine", definition: "Kept secret or done secretively", partOfSpeech: "adjective", example: "They held clandestine meetings after dark." },
  { word: "clemency", definition: "Mercy; lenience", partOfSpeech: "noun", example: "The governor granted clemency to the prisoner." },
  { word: "coalesce", definition: "To come together to form one mass or whole", partOfSpeech: "verb", example: "The opposition parties coalesced to form a coalition." },
  { word: "cogent", definition: "Clear, logical, and convincing", partOfSpeech: "adjective", example: "She made a cogent argument for the proposal." },
  { word: "complacent", definition: "Showing smug satisfaction with oneself", partOfSpeech: "adjective", example: "Success made him complacent about his studies." },
  { word: "conciliatory", definition: "Intended to placate or pacify", partOfSpeech: "adjective", example: "His conciliatory tone helped ease tensions." },
  { word: "condone", definition: "To accept and allow behavior to continue", partOfSpeech: "verb", example: "The school does not condone bullying." },
  { word: "conflagration", definition: "An extensive fire that destroys a great deal", partOfSpeech: "noun", example: "The conflagration destroyed the entire forest." },
  { word: "congenial", definition: "Pleasant because of a personality similar to one's own", partOfSpeech: "adjective", example: "The congenial atmosphere made work enjoyable." },
  { word: "connive", definition: "To secretly allow something to occur", partOfSpeech: "verb", example: "Officials were accused of conniving in the fraud." },
  { word: "contentious", definition: "Causing or likely to cause an argument", partOfSpeech: "adjective", example: "The contentious debate lasted for hours." },
  { word: "contrite", definition: "Feeling or expressing remorse", partOfSpeech: "adjective", example: "He was contrite after realizing his mistake." },
  { word: "conundrum", definition: "A confusing and difficult problem or question", partOfSpeech: "noun", example: "The detective faced a puzzling conundrum." },
  { word: "copious", definition: "Abundant in supply or quantity", partOfSpeech: "adjective", example: "She took copious notes during the lecture." },
  { word: "corroborate", definition: "To confirm or give support to a statement", partOfSpeech: "verb", example: "The witness corroborated the defendant's alibi." },
  { word: "credulous", definition: "Having a tendency to believe things too readily", partOfSpeech: "adjective", example: "The credulous tourist fell for every scam." },
  { word: "culpable", definition: "Deserving blame", partOfSpeech: "adjective", example: "Both parties were found culpable in the accident." },
  { word: "cursory", definition: "Hasty and therefore not thorough", partOfSpeech: "adjective", example: "A cursory glance revealed nothing unusual." },
  { word: "cynical", definition: "Believing that people are motivated purely by self-interest", partOfSpeech: "adjective", example: "Years of disappointment made her cynical about politics." },
  { word: "dauntless", definition: "Showing fearlessness and determination", partOfSpeech: "adjective", example: "The dauntless explorer ventured into unknown territory." },
  { word: "debacle", definition: "A sudden and ignominious failure", partOfSpeech: "noun", example: "The product launch was a complete debacle." },
  { word: "decorum", definition: "Behavior in keeping with good taste and propriety", partOfSpeech: "noun", example: "Guests were expected to maintain decorum at the event." },
  { word: "deferential", definition: "Showing respect and esteem", partOfSpeech: "adjective", example: "The staff was deferential to the visiting dignitary." },
  { word: "defunct", definition: "No longer existing or functioning", partOfSpeech: "adjective", example: "The defunct company left many employees jobless." },
  { word: "deleterious", definition: "Causing harm or damage", partOfSpeech: "adjective", example: "Smoking has deleterious effects on health." },
  { word: "delineate", definition: "To describe or portray something precisely", partOfSpeech: "verb", example: "The contract clearly delineates each party's responsibilities." },
  { word: "demagogue", definition: "A political leader who seeks support by appealing to emotions", partOfSpeech: "noun", example: "The demagogue stirred up fears to gain votes." },
  { word: "demure", definition: "Reserved, modest, and shy", partOfSpeech: "adjective", example: "Her demure smile charmed everyone at the party." },
  { word: "denigrate", definition: "To criticize unfairly; disparage", partOfSpeech: "verb", example: "He attempted to denigrate his opponent's reputation." },
  { word: "deprecate", definition: "To express disapproval of", partOfSpeech: "verb", example: "She deprecated the use of violence in protests." },
  { word: "deride", definition: "To express contempt for; ridicule", partOfSpeech: "verb", example: "Critics derided the film as unoriginal." },
  { word: "derivative", definition: "Imitative of the work of another person", partOfSpeech: "adjective", example: "The artist's work was criticized as derivative." },
  { word: "despondent", definition: "In low spirits from loss of hope", partOfSpeech: "adjective", example: "He became despondent after losing his job." },
  { word: "despot", definition: "A ruler with total power, often cruel", partOfSpeech: "noun", example: "The despot ruled the country with an iron fist." },
  { word: "deter", definition: "To discourage someone from doing something", partOfSpeech: "verb", example: "High prices deter many potential buyers." },
  { word: "diatribe", definition: "A forceful and bitter verbal attack", partOfSpeech: "noun", example: "The editorial was a diatribe against corruption." },
  { word: "didactic", definition: "Intended to teach, particularly moral instruction", partOfSpeech: "adjective", example: "The novel's didactic tone annoyed some readers." },
  { word: "diffident", definition: "Modest or shy because of a lack of self-confidence", partOfSpeech: "adjective", example: "The diffident student rarely spoke in class." },
  { word: "diligent", definition: "Having or showing care in one's work", partOfSpeech: "adjective", example: "Her diligent research uncovered new evidence." },
  { word: "discerning", definition: "Having or showing good judgment", partOfSpeech: "adjective", example: "The discerning critic praised the subtle performances." },
  { word: "disparate", definition: "Essentially different in kind", partOfSpeech: "adjective", example: "The study combined data from disparate sources." },
  { word: "disseminate", definition: "To spread or disperse widely", partOfSpeech: "verb", example: "The organization disseminates health information." },
  { word: "dissonance", definition: "Lack of harmony; discord", partOfSpeech: "noun", example: "There was dissonance between his words and actions." },
  { word: "dogmatic", definition: "Inclined to lay down principles as undeniable", partOfSpeech: "adjective", example: "His dogmatic approach alienated potential allies." },
  { word: "dubious", definition: "Hesitating or doubting; not reliable", partOfSpeech: "adjective", example: "The claim was based on dubious evidence." },
  { word: "ebullient", definition: "Cheerful and full of energy", partOfSpeech: "adjective", example: "Her ebullient personality lit up the room." },
  { word: "eclectic", definition: "Deriving ideas from a broad range of sources", partOfSpeech: "adjective", example: "The restaurant offers an eclectic menu." },
  { word: "efficacy", definition: "The ability to produce a desired result", partOfSpeech: "noun", example: "Studies confirmed the efficacy of the treatment." },
  { word: "effrontery", definition: "Insolent or impertinent behavior", partOfSpeech: "noun", example: "She had the effrontery to demand a raise after arriving late." },
  { word: "egregious", definition: "Outstandingly bad; shocking", partOfSpeech: "adjective", example: "The report revealed egregious violations of safety codes." },
  { word: "elicit", definition: "To draw out a response or reaction", partOfSpeech: "verb", example: "The comedian's jokes elicited loud laughter." },
  { word: "eloquent", definition: "Fluent or persuasive in speaking or writing", partOfSpeech: "adjective", example: "Her eloquent speech moved the audience to tears." },
  { word: "elucidate", definition: "To make something clear; explain", partOfSpeech: "verb", example: "The professor elucidated the complex theory." },
  { word: "emulate", definition: "To match or surpass by imitation", partOfSpeech: "verb", example: "Young athletes often emulate their sports heroes." },
  { word: "endemic", definition: "Native to a particular place", partOfSpeech: "adjective", example: "Corruption is endemic in some industries." },
  { word: "enervate", definition: "To cause someone to feel drained of energy", partOfSpeech: "verb", example: "The humid weather enervated the travelers." },
  { word: "enigmatic", definition: "Difficult to interpret or understand; mysterious", partOfSpeech: "adjective", example: "The Mona Lisa's enigmatic smile has puzzled viewers for centuries." },
  { word: "ennui", definition: "A feeling of listlessness from lack of excitement", partOfSpeech: "noun", example: "Summer ennui set in after weeks without plans." },
  { word: "ephemeral", definition: "Lasting for a very short time", partOfSpeech: "adjective", example: "Fame can be ephemeral in the entertainment industry." },
  { word: "equanimity", definition: "Mental calmness, especially in difficult situations", partOfSpeech: "noun", example: "She faced the crisis with remarkable equanimity." },
  { word: "equivocal", definition: "Open to more than one interpretation; ambiguous", partOfSpeech: "adjective", example: "His equivocal response left us unsure of his intentions." },
  { word: "erudite", definition: "Having or showing great knowledge", partOfSpeech: "adjective", example: "The erudite professor impressed students with his vast knowledge." },
  { word: "esoteric", definition: "Intended for or understood by only a small group", partOfSpeech: "adjective", example: "The book delves into esoteric philosophy." },
  { word: "euphemism", definition: "A mild expression substituted for a harsh one", partOfSpeech: "noun", example: "'Passed away' is a euphemism for 'died.'" },
  { word: "exacerbate", definition: "To make a problem or situation worse", partOfSpeech: "verb", example: "The drought exacerbated the food shortage." },
  { word: "exculpate", definition: "To show or declare that someone is not guilty", partOfSpeech: "verb", example: "New evidence exculpated the defendant." },
  { word: "exemplary", definition: "Serving as a desirable model; outstanding", partOfSpeech: "adjective", example: "Her exemplary conduct earned her a promotion." },
  { word: "exigent", definition: "Pressing; demanding immediate action", partOfSpeech: "adjective", example: "The exigent circumstances required a quick decision." },
  { word: "exonerate", definition: "To absolve someone from blame", partOfSpeech: "verb", example: "DNA evidence exonerated the wrongly convicted man." },
  { word: "expedient", definition: "Convenient and practical but possibly improper", partOfSpeech: "adjective", example: "Taking a shortcut seemed expedient at the time." },
  { word: "explicable", definition: "Able to be accounted for or understood", partOfSpeech: "adjective", example: "The phenomenon is easily explicable by science." },
  { word: "extol", definition: "To praise enthusiastically", partOfSpeech: "verb", example: "Critics extolled the director's latest film." },
  { word: "facetious", definition: "Treating serious issues with inappropriate humor", partOfSpeech: "adjective", example: "His facetious remarks during the meeting were unwelcome." },
  { word: "fallacious", definition: "Based on a mistaken belief", partOfSpeech: "adjective", example: "The argument was built on fallacious assumptions." },
  { word: "fastidious", definition: "Very attentive to detail; meticulous", partOfSpeech: "adjective", example: "The fastidious chef inspected every ingredient." },
  { word: "fathom", definition: "To understand after much thought", partOfSpeech: "verb", example: "I cannot fathom why he made that decision." },
  { word: "fatuous", definition: "Silly and pointless", partOfSpeech: "adjective", example: "The fatuous comment added nothing to the discussion." },
  { word: "fecund", definition: "Producing or capable of producing abundantly", partOfSpeech: "adjective", example: "The fecund soil yielded an impressive harvest." },
  { word: "felicitous", definition: "Well-chosen or suited to the circumstances", partOfSpeech: "adjective", example: "Her felicitous words brought comfort to the grieving family." },
  { word: "fervent", definition: "Having or displaying passionate intensity", partOfSpeech: "adjective", example: "She was a fervent advocate for animal rights." },
  { word: "fickle", definition: "Changing frequently, especially regarding loyalties", partOfSpeech: "adjective", example: "The fickle audience quickly moved on to the next trend." },
  { word: "flagrant", definition: "Conspicuously offensive", partOfSpeech: "adjective", example: "The referee called a flagrant foul on the player." },
  { word: "florid", definition: "Having a red or flushed complexion; elaborate", partOfSpeech: "adjective", example: "The author's florid prose was difficult to read." },
  { word: "flout", definition: "To openly disregard a rule or convention", partOfSpeech: "verb", example: "Protesters flouted the curfew order." },
  { word: "fortuitous", definition: "Happening by chance, especially a lucky chance", partOfSpeech: "adjective", example: "A fortuitous meeting led to a business partnership." },
  { word: "frivolous", definition: "Not having any serious purpose or value", partOfSpeech: "adjective", example: "The lawsuit was dismissed as frivolous." },
  { word: "frugal", definition: "Sparing or economical with regard to resources", partOfSpeech: "adjective", example: "Her frugal habits helped her save for retirement." },
  { word: "furtive", definition: "Attempting to avoid notice or attention", partOfSpeech: "adjective", example: "He cast a furtive glance at the door." },
  { word: "garrulous", definition: "Excessively talkative, especially on trivial matters", partOfSpeech: "adjective", example: "The garrulous neighbor talked for hours about nothing." },
  { word: "germane", definition: "Relevant to a subject under consideration", partOfSpeech: "adjective", example: "Her comments were not germane to the discussion." },
  { word: "glean", definition: "To extract information from various sources", partOfSpeech: "verb", example: "Researchers gleaned data from hundreds of interviews." },
  { word: "glib", definition: "Fluent but insincere and shallow", partOfSpeech: "adjective", example: "His glib explanations failed to convince anyone." },
  { word: "grandiloquent", definition: "Using pompous or extravagant language", partOfSpeech: "adjective", example: "The grandiloquent speech was full of empty rhetoric." },
  { word: "gratuitous", definition: "Uncalled for; lacking good reason", partOfSpeech: "adjective", example: "The film contained gratuitous violence." },
  { word: "gregarious", definition: "Fond of company; sociable", partOfSpeech: "adjective", example: "His gregarious nature made him popular at parties." },
  { word: "guileless", definition: "Innocent and without deception", partOfSpeech: "adjective", example: "Her guileless smile put everyone at ease." },
  { word: "hackneyed", definition: "Lacking significance through overuse", partOfSpeech: "adjective", example: "The movie relied on hackneyed plot devices." },
  { word: "harangue", definition: "A lengthy and aggressive speech", partOfSpeech: "noun", example: "The politician launched into a harangue against the opposition." },
  { word: "harbinger", definition: "A person or thing announcing the approach of another", partOfSpeech: "noun", example: "The robin is a harbinger of spring." },
  { word: "hedonist", definition: "A person who believes pleasure is the most important thing", partOfSpeech: "noun", example: "The hedonist spent lavishly on luxuries." },
  { word: "heinous", definition: "Utterly odious or wicked", partOfSpeech: "adjective", example: "The heinous crime shocked the entire community." },
  { word: "heresy", definition: "Opinion profoundly at odds with accepted belief", partOfSpeech: "noun", example: "His theories were considered heresy by the establishment." },
  { word: "heterogeneous", definition: "Diverse in character or content", partOfSpeech: "adjective", example: "The city has a heterogeneous population." },
  { word: "hiatus", definition: "A pause or gap in a sequence", partOfSpeech: "noun", example: "The band took a hiatus after their world tour." },
  { word: "hyperbole", definition: "Exaggerated statements not meant to be taken literally", partOfSpeech: "noun", example: "Saying you're 'starving' is often hyperbole." },
  { word: "iconoclast", definition: "A person who attacks cherished beliefs or institutions", partOfSpeech: "noun", example: "The artist was an iconoclast who challenged conventions." },
  { word: "idiosyncrasy", definition: "A distinctive or peculiar characteristic", partOfSpeech: "noun", example: "One of his idiosyncrasies was collecting vintage typewriters." },
  { word: "ignominious", definition: "Deserving or causing public disgrace", partOfSpeech: "adjective", example: "The team suffered an ignominious defeat." },
  { word: "illicit", definition: "Forbidden by law, rules, or custom", partOfSpeech: "adjective", example: "The police uncovered illicit activities at the warehouse." },
  { word: "immutable", definition: "Unchanging over time or unable to be changed", partOfSpeech: "adjective", example: "The laws of physics are immutable." },
  { word: "impartial", definition: "Treating all rivals or disputants equally", partOfSpeech: "adjective", example: "A judge must remain impartial during a trial." },
  { word: "impeccable", definition: "Faultless; in accordance with the highest standards", partOfSpeech: "adjective", example: "Her impeccable taste in fashion was widely admired." },
  { word: "impede", definition: "To delay or prevent by obstructing", partOfSpeech: "verb", example: "Bad weather impeded the rescue efforts." },
  { word: "impervious", definition: "Not allowing fluid to pass through; unaffected", partOfSpeech: "adjective", example: "He seemed impervious to criticism." },
  { word: "impetuous", definition: "Acting quickly without thought or care", partOfSpeech: "adjective", example: "His impetuous decision cost him dearly." },
  { word: "implacable", definition: "Unable to be placated or appeased", partOfSpeech: "adjective", example: "She was implacable in her demands for justice." },
  { word: "implicit", definition: "Implied though not plainly expressed", partOfSpeech: "adjective", example: "There was an implicit understanding between them." },
  { word: "impudent", definition: "Not showing due respect for another person", partOfSpeech: "adjective", example: "The impudent child talked back to the teacher." },
  { word: "inchoate", definition: "Just begun and not fully formed", partOfSpeech: "adjective", example: "The plan was still inchoate and needed refinement." },
  { word: "incisive", definition: "Intelligently analytical and clear-thinking", partOfSpeech: "adjective", example: "Her incisive analysis impressed the board." },
  { word: "incongruous", definition: "Not in harmony or keeping with the surroundings", partOfSpeech: "adjective", example: "The modern sculpture looked incongruous in the historic square." },
  { word: "indefatigable", definition: "Persisting tirelessly", partOfSpeech: "adjective", example: "The indefatigable volunteer worked around the clock." },
  { word: "indigent", definition: "Poor; needy", partOfSpeech: "adjective", example: "The charity provides services to indigent families." },
  { word: "indolent", definition: "Wanting to avoid activity or exertion; lazy", partOfSpeech: "adjective", example: "His indolent attitude prevented him from succeeding." },
  { word: "ineffable", definition: "Too great to be expressed in words", partOfSpeech: "adjective", example: "She felt ineffable joy at seeing her grandchildren." },
  { word: "inept", definition: "Having or showing no skill; clumsy", partOfSpeech: "adjective", example: "The inept handling of the crisis made things worse." },
  { word: "inexorable", definition: "Impossible to stop or prevent", partOfSpeech: "adjective", example: "The inexorable march of time changes everything." },
  { word: "ingenuous", definition: "Innocent and unsuspecting", partOfSpeech: "adjective", example: "His ingenuous questions revealed his inexperience." },
  { word: "innate", definition: "Inborn; natural", partOfSpeech: "adjective", example: "She has an innate talent for music." },
  { word: "innocuous", definition: "Not harmful or offensive", partOfSpeech: "adjective", example: "The innocuous comment was taken out of context." },
  { word: "insidious", definition: "Proceeding in a subtle way but with harmful effects", partOfSpeech: "adjective", example: "The insidious disease went undetected for years." },
  { word: "insipid", definition: "Lacking flavor or vigor", partOfSpeech: "adjective", example: "The insipid soup needed more seasoning." },
  { word: "intransigent", definition: "Unwilling to change one's views", partOfSpeech: "adjective", example: "The intransigent negotiators reached no agreement." },
  { word: "intrepid", definition: "Fearless; adventurous", partOfSpeech: "adjective", example: "The intrepid journalist reported from the war zone." },
  { word: "inundate", definition: "To overwhelm with things to be dealt with", partOfSpeech: "verb", example: "The company was inundated with applications." },
  { word: "inveterate", definition: "Having a particular habit that is unlikely to change", partOfSpeech: "adjective", example: "He was an inveterate gambler who couldn't quit." },
  { word: "irascible", definition: "Having a tendency to be easily angered", partOfSpeech: "adjective", example: "The irascible professor intimidated students." },
  { word: "juxtapose", definition: "To place side by side for comparison", partOfSpeech: "verb", example: "The exhibit juxtaposed classical and modern art." },
  { word: "laconic", definition: "Using very few words", partOfSpeech: "adjective", example: "His laconic replies gave nothing away." },
  { word: "languid", definition: "Displaying a lack of energy", partOfSpeech: "adjective", example: "The languid summer afternoon passed slowly." },
  { word: "laud", definition: "To praise highly", partOfSpeech: "verb", example: "Critics lauded the author's latest novel." },
  { word: "lethargic", definition: "Affected by lethargy; sluggish", partOfSpeech: "adjective", example: "The heat made everyone feel lethargic." },
  { word: "litigious", definition: "Tending to go to law to settle disputes", partOfSpeech: "adjective", example: "The litigious company sued over every minor issue." },
  { word: "lucid", definition: "Expressed clearly; easy to understand", partOfSpeech: "adjective", example: "The lucid explanation helped students grasp the concept." },
  { word: "magnanimous", definition: "Very generous or forgiving", partOfSpeech: "adjective", example: "The magnanimous winner congratulated his opponent." },
  { word: "malevolent", definition: "Having or showing a wish to do evil", partOfSpeech: "adjective", example: "The villain had a malevolent grin." },
  { word: "malleable", definition: "Easily influenced; pliable", partOfSpeech: "adjective", example: "Young minds are malleable and impressionable." },
  { word: "meticulous", definition: "Showing great attention to detail", partOfSpeech: "adjective", example: "She kept meticulous records of every transaction." },
  { word: "misanthrope", definition: "A person who dislikes humankind", partOfSpeech: "noun", example: "The misanthrope preferred the company of animals." },
  { word: "mitigate", definition: "To make less severe, serious, or painful", partOfSpeech: "verb", example: "Medication can mitigate the symptoms." },
  { word: "mundane", definition: "Lacking interest or excitement; dull", partOfSpeech: "adjective", example: "She longed to escape her mundane routine." },
  { word: "nebulous", definition: "Vague or ill-defined", partOfSpeech: "adjective", example: "The plans remained nebulous and unformed." },
  { word: "nefarious", definition: "Wicked or criminal", partOfSpeech: "adjective", example: "The villain's nefarious plot was thwarted." },
  { word: "neophyte", definition: "A person who is new to a subject or activity", partOfSpeech: "noun", example: "The neophyte struggled with advanced concepts." },
  { word: "nonchalant", definition: "Appearing casually calm and relaxed", partOfSpeech: "adjective", example: "He gave a nonchalant shrug when asked about it." },
  { word: "nostalgia", definition: "Sentimental longing for the past", partOfSpeech: "noun", example: "Looking at old photos filled her with nostalgia." },
  { word: "obdurate", definition: "Stubbornly refusing to change one's opinion", partOfSpeech: "adjective", example: "The obdurate child refused to apologize." },
  { word: "obfuscate", definition: "To render obscure or unclear", partOfSpeech: "verb", example: "Technical jargon can obfuscate simple concepts." },
  { word: "obsequious", definition: "Obedient or attentive to an excessive degree", partOfSpeech: "adjective", example: "The obsequious assistant agreed with everything." },
  { word: "obsolete", definition: "No longer produced or used; out of date", partOfSpeech: "adjective", example: "The technology became obsolete within a decade." },
  { word: "obstinate", definition: "Stubbornly refusing to change", partOfSpeech: "adjective", example: "Her obstinate refusal frustrated her colleagues." },
  { word: "opulent", definition: "Ostentatiously rich and luxurious", partOfSpeech: "adjective", example: "The opulent mansion featured a marble foyer." },
  { word: "ostentatious", definition: "Characterized by showy display", partOfSpeech: "adjective", example: "His ostentatious wealth made others uncomfortable." },
  { word: "panacea", definition: "A solution for all difficulties", partOfSpeech: "noun", example: "There is no panacea for the economic crisis." },
  { word: "paradigm", definition: "A typical example or pattern of something", partOfSpeech: "noun", example: "This discovery represents a new paradigm in science." },
  { word: "paragon", definition: "A model of excellence or perfection", partOfSpeech: "noun", example: "She was considered a paragon of virtue." },
  { word: "parsimonious", definition: "Unwilling to spend money; stingy", partOfSpeech: "adjective", example: "The parsimonious manager rarely approved expenses." },
  { word: "pedantic", definition: "Excessively concerned with minor details", partOfSpeech: "adjective", example: "His pedantic corrections annoyed everyone." },
  { word: "penchant", definition: "A strong or habitual liking for something", partOfSpeech: "noun", example: "She has a penchant for dramatic gestures." },
  { word: "penitent", definition: "Feeling or showing sorrow for wrongdoing", partOfSpeech: "adjective", example: "The penitent thief returned what he had stolen." },
  { word: "perfidious", definition: "Deceitful and untrustworthy", partOfSpeech: "adjective", example: "The perfidious spy betrayed his country." },
  { word: "perfunctory", definition: "Carried out with minimum effort", partOfSpeech: "adjective", example: "He gave the report only a perfunctory glance." },
  { word: "pernicious", definition: "Having a harmful effect, especially gradually", partOfSpeech: "adjective", example: "The pernicious influence corrupted the organization." },
  { word: "perspicacious", definition: "Having a ready insight into things", partOfSpeech: "adjective", example: "The perspicacious detective solved the case quickly." },
  { word: "pertinent", definition: "Relevant or applicable to a matter", partOfSpeech: "adjective", example: "Please keep your comments pertinent to the topic." },
  { word: "pervasive", definition: "Spreading widely throughout an area", partOfSpeech: "adjective", example: "Technology has become pervasive in daily life." },
  { word: "petulant", definition: "Childishly sulky or bad-tempered", partOfSpeech: "adjective", example: "His petulant behavior annoyed his coworkers." },
  { word: "placate", definition: "To make someone less angry or hostile", partOfSpeech: "verb", example: "She tried to placate the upset customer." },
  { word: "platitude", definition: "A remark that has been used too often", partOfSpeech: "noun", example: "The speech was full of platitudes and clichés." },
  { word: "plethora", definition: "A large or excessive amount of something", partOfSpeech: "noun", example: "There is a plethora of options to choose from." },
  { word: "polemical", definition: "Of or involving strongly critical or controversial writing", partOfSpeech: "adjective", example: "The polemical essay sparked heated debate." },
  { word: "pragmatic", definition: "Dealing with things sensibly and realistically", partOfSpeech: "adjective", example: "She took a pragmatic approach to problem-solving." },
  { word: "precarious", definition: "Not securely held; dangerously uncertain", partOfSpeech: "adjective", example: "The mountain climber was in a precarious position." },
  { word: "precipitate", definition: "To cause to happen suddenly or unexpectedly", partOfSpeech: "verb", example: "The scandal precipitated his resignation." },
  { word: "preclude", definition: "To prevent from happening", partOfSpeech: "verb", example: "The injury precluded her from competing." },
  { word: "precocious", definition: "Having developed certain abilities earlier than usual", partOfSpeech: "adjective", example: "The precocious child was reading at age three." },
  { word: "predilection", definition: "A preference or special liking", partOfSpeech: "noun", example: "He had a predilection for spicy food." },
  { word: "prescient", definition: "Having knowledge of events before they occur", partOfSpeech: "adjective", example: "The prescient author predicted many modern technologies." },
  { word: "presumptuous", definition: "Failing to observe limits of what is appropriate", partOfSpeech: "adjective", example: "It was presumptuous of him to assume he'd be invited." },
  { word: "prevaricate", definition: "To speak or act evasively", partOfSpeech: "verb", example: "The witness prevaricated when questioned." },
  { word: "pristine", definition: "In its original condition; unspoiled", partOfSpeech: "adjective", example: "The pristine beach had no footprints in the sand." },
  { word: "probity", definition: "The quality of having strong moral principles", partOfSpeech: "noun", example: "Her probity was never questioned." },
  { word: "proclivity", definition: "A tendency to choose or do something regularly", partOfSpeech: "noun", example: "He has a proclivity for telling tall tales." },
  { word: "prodigal", definition: "Spending money or resources freely and recklessly", partOfSpeech: "adjective", example: "The prodigal heir squandered his inheritance." },
  { word: "prodigious", definition: "Remarkably great in extent, size, or degree", partOfSpeech: "adjective", example: "She possessed prodigious talent for mathematics." },
  { word: "profligate", definition: "Recklessly extravagant or wasteful", partOfSpeech: "adjective", example: "His profligate spending depleted his savings." },
  { word: "profound", definition: "Very great or intense; having deep insight", partOfSpeech: "adjective", example: "The book had a profound impact on her thinking." },
  { word: "profuse", definition: "Exuberantly plentiful; abundant", partOfSpeech: "adjective", example: "She offered profuse apologies for the mistake." },
  { word: "proliferate", definition: "To increase rapidly in numbers", partOfSpeech: "verb", example: "Social media platforms have proliferated in recent years." },
  { word: "prolific", definition: "Producing much fruit, foliage, or offspring", partOfSpeech: "adjective", example: "The prolific author published twenty novels." },
  { word: "propensity", definition: "An inclination or natural tendency", partOfSpeech: "noun", example: "He has a propensity for exaggeration." },
  { word: "propitious", definition: "Giving or indicating a good chance of success", partOfSpeech: "adjective", example: "The conditions were propitious for a good harvest." },
  { word: "prosaic", definition: "Having the style of prose; lacking poetic beauty", partOfSpeech: "adjective", example: "The prosaic description failed to capture the scene's beauty." },
  { word: "proscribe", definition: "To forbid, especially by law", partOfSpeech: "verb", example: "The treaty proscribes the use of chemical weapons." },
  { word: "provincial", definition: "Of or concerning a province; unsophisticated", partOfSpeech: "adjective", example: "His provincial attitudes seemed out of place in the city." },
  { word: "prudent", definition: "Acting with care and thought for the future", partOfSpeech: "adjective", example: "It's prudent to save money for emergencies." },
  { word: "pugnacious", definition: "Eager or quick to argue, quarrel, or fight", partOfSpeech: "adjective", example: "The pugnacious debater never backed down." },
  { word: "punctilious", definition: "Showing great attention to detail or correct behavior", partOfSpeech: "adjective", example: "The punctilious accountant reviewed every entry." },
  { word: "pungent", definition: "Having a sharply strong taste or smell", partOfSpeech: "adjective", example: "The pungent aroma of garlic filled the kitchen." },
  { word: "quagmire", definition: "A soft boggy area of land; a difficult situation", partOfSpeech: "noun", example: "The project became a bureaucratic quagmire." },
  { word: "querulous", definition: "Complaining in a petulant manner", partOfSpeech: "adjective", example: "The querulous patient complained about everything." },
  { word: "quixotic", definition: "Exceedingly idealistic; unrealistic", partOfSpeech: "adjective", example: "His quixotic dreams never came to fruition." },
  { word: "rancorous", definition: "Characterized by bitterness or resentment", partOfSpeech: "adjective", example: "The rancorous dispute divided the family." },
  { word: "recalcitrant", definition: "Having an obstinately uncooperative attitude", partOfSpeech: "adjective", example: "The recalcitrant student refused to follow rules." },
  { word: "recondite", definition: "Little known; abstruse", partOfSpeech: "adjective", example: "The scholar specialized in recondite subjects." },
  { word: "redundant", definition: "Not or no longer needed or useful; superfluous", partOfSpeech: "adjective", example: "The redundant information was edited out." },
  { word: "refute", definition: "To prove a statement or theory to be wrong", partOfSpeech: "verb", example: "The evidence refuted the defendant's claims." },
  { word: "relegate", definition: "To consign to a lower position", partOfSpeech: "verb", example: "The experienced player was relegated to the bench." },
  { word: "replete", definition: "Filled or well-supplied with something", partOfSpeech: "adjective", example: "The buffet was replete with delicious options." },
  { word: "reprehensible", definition: "Deserving censure or condemnation", partOfSpeech: "adjective", example: "His reprehensible behavior shocked everyone." },
  { word: "repudiate", definition: "To refuse to accept or be associated with", partOfSpeech: "verb", example: "The candidate repudiated the extremist group's endorsement." },
  { word: "rescind", definition: "To revoke, cancel, or repeal", partOfSpeech: "verb", example: "The company rescinded the job offer." },
  { word: "resilient", definition: "Able to recover quickly from difficulties", partOfSpeech: "adjective", example: "The resilient community rebuilt after the disaster." },
  { word: "resolute", definition: "Admirably purposeful and determined", partOfSpeech: "adjective", example: "She was resolute in her decision to quit." },
  { word: "reticent", definition: "Not revealing one's thoughts or feelings readily", partOfSpeech: "adjective", example: "He was reticent about his past experiences." },
  { word: "rhetoric", definition: "The art of effective or persuasive speaking", partOfSpeech: "noun", example: "The politician's rhetoric inspired the crowd." },
  { word: "sagacious", definition: "Having keen mental discernment and good judgment", partOfSpeech: "adjective", example: "The sagacious advisor offered wise counsel." },
  { word: "salient", definition: "Most noticeable or important", partOfSpeech: "adjective", example: "The report highlighted the salient points." },
  { word: "sanction", definition: "To give official permission or approval", partOfSpeech: "verb", example: "The committee sanctioned the new policy." },
  { word: "sardonic", definition: "Grimly mocking or cynical", partOfSpeech: "adjective", example: "His sardonic smile suggested he knew more than he revealed." },
  { word: "sartorial", definition: "Relating to tailoring, clothes, or style of dress", partOfSpeech: "adjective", example: "His sartorial elegance was always admired." },
  { word: "satiate", definition: "To satisfy fully", partOfSpeech: "verb", example: "The large meal satiated our hunger completely." },
  { word: "scrupulous", definition: "Diligent, thorough, and attentive to details", partOfSpeech: "adjective", example: "The scrupulous researcher verified every source." },
  { word: "scrutinize", definition: "To examine or inspect closely and thoroughly", partOfSpeech: "verb", example: "The editor scrutinized the manuscript for errors." },
  { word: "sedulous", definition: "Showing dedication and diligence", partOfSpeech: "adjective", example: "Her sedulous efforts eventually paid off." },
  { word: "seminal", definition: "Strongly influencing later developments", partOfSpeech: "adjective", example: "His seminal work changed the field forever." },
  { word: "sententious", definition: "Given to moralizing in a pompous manner", partOfSpeech: "adjective", example: "The sententious speech bored the audience." },
  { word: "serendipity", definition: "The occurrence of events by chance in a happy way", partOfSpeech: "noun", example: "Meeting her was pure serendipity." },
  { word: "servile", definition: "Having an excessive willingness to serve others", partOfSpeech: "adjective", example: "His servile attitude disgusted his colleagues." },
  { word: "skeptical", definition: "Not easily convinced; having doubts", partOfSpeech: "adjective", example: "She was skeptical of his claims." },
  { word: "solicitous", definition: "Characterized by concern or attention", partOfSpeech: "adjective", example: "The solicitous nurse checked on patients frequently." },
  { word: "somnolent", definition: "Sleepy; drowsy", partOfSpeech: "adjective", example: "The somnolent students struggled to stay awake." },
  { word: "specious", definition: "Superficially plausible but actually wrong", partOfSpeech: "adjective", example: "His specious argument fooled no one." },
  { word: "sporadic", definition: "Occurring at irregular intervals", partOfSpeech: "adjective", example: "Sporadic gunfire could be heard in the distance." },
  { word: "spurious", definition: "Not genuine; false or fake", partOfSpeech: "adjective", example: "The spurious claims were quickly debunked." },
  { word: "stagnant", definition: "Showing no activity; still", partOfSpeech: "adjective", example: "The stagnant economy showed no signs of growth." },
  { word: "staunch", definition: "Loyal and committed in attitude", partOfSpeech: "adjective", example: "She remained a staunch supporter despite criticism." },
  { word: "stigmatize", definition: "To describe or regard as worthy of disgrace", partOfSpeech: "verb", example: "Society often stigmatizes mental illness." },
  { word: "stoic", definition: "Enduring pain without complaint", partOfSpeech: "adjective", example: "He remained stoic throughout the ordeal." },
  { word: "strident", definition: "Loud and harsh; forceful", partOfSpeech: "adjective", example: "Her strident voice commanded attention." },
  { word: "stringent", definition: "Strict, precise, and exacting", partOfSpeech: "adjective", example: "The lab has stringent safety protocols." },
  { word: "subjugate", definition: "To bring under domination or control", partOfSpeech: "verb", example: "The empire sought to subjugate neighboring kingdoms." },
  { word: "sublime", definition: "Of outstanding spiritual or artistic worth", partOfSpeech: "adjective", example: "The sunset over the ocean was sublime." },
  { word: "substantiate", definition: "To provide evidence to support a claim", partOfSpeech: "verb", example: "The documents substantiated her accusations." },
  { word: "subversive", definition: "Seeking to undermine an established system", partOfSpeech: "adjective", example: "The regime considered the book subversive." },
  { word: "succinct", definition: "Briefly and clearly expressed", partOfSpeech: "adjective", example: "Please give a succinct summary of the report." },
  { word: "supercilious", definition: "Behaving as if one thinks one is superior", partOfSpeech: "adjective", example: "The supercilious waiter looked down on customers." },
  { word: "superfluous", definition: "Unnecessary, especially through excess", partOfSpeech: "adjective", example: "The editor removed all superfluous words." },
  { word: "supplant", definition: "To supersede and replace", partOfSpeech: "verb", example: "Email has largely supplanted traditional mail." },
  { word: "surreptitious", definition: "Kept secret because it would not be approved", partOfSpeech: "adjective", example: "She took a surreptitious glance at the answers." },
  { word: "sycophant", definition: "A person who acts obsequiously to gain advantage", partOfSpeech: "noun", example: "The boss was surrounded by sycophants." },
  { word: "tacit", definition: "Understood without being stated", partOfSpeech: "adjective", example: "There was a tacit agreement between them." },
  { word: "taciturn", definition: "Reserved or uncommunicative in speech", partOfSpeech: "adjective", example: "The taciturn man rarely spoke at meetings." },
  { word: "tangential", definition: "Barely touching a subject; peripheral", partOfSpeech: "adjective", example: "His comments were tangential to the main issue." },
  { word: "tantamount", definition: "Equivalent in seriousness to; virtually the same as", partOfSpeech: "adjective", example: "His silence was tantamount to an admission of guilt." },
  { word: "temerity", definition: "Excessive confidence or boldness", partOfSpeech: "noun", example: "She had the temerity to challenge the CEO." },
  { word: "temperate", definition: "Showing moderation or self-restraint", partOfSpeech: "adjective", example: "His temperate response surprised his critics." },
  { word: "tenacious", definition: "Holding firmly to something; persistent", partOfSpeech: "adjective", example: "The tenacious reporter uncovered the scandal." },
  { word: "terse", definition: "Sparing in the use of words; abrupt", partOfSpeech: "adjective", example: "His terse reply suggested annoyance." },
  { word: "timorous", definition: "Showing nervousness or lack of confidence", partOfSpeech: "adjective", example: "The timorous speaker avoided eye contact." },
  { word: "torpid", definition: "Mentally or physically inactive; sluggish", partOfSpeech: "adjective", example: "The torpid bear slept through winter." },
  { word: "tractable", definition: "Easy to control or influence", partOfSpeech: "adjective", example: "The tractable puppy learned commands quickly." },
  { word: "transient", definition: "Lasting only for a short time", partOfSpeech: "adjective", example: "Fame is often transient in nature." },
  { word: "trepidation", definition: "A feeling of fear about something that may happen", partOfSpeech: "noun", example: "She approached the exam with trepidation." },
  { word: "truculent", definition: "Eager or quick to argue or fight", partOfSpeech: "adjective", example: "The truculent customer made a scene." },
  { word: "ubiquitous", definition: "Present, appearing, or found everywhere", partOfSpeech: "adjective", example: "Smartphones have become ubiquitous in society." },
  { word: "unctuous", definition: "Excessively flattering or ingratiating", partOfSpeech: "adjective", example: "The unctuous salesman made her uncomfortable." },
  { word: "undermine", definition: "To erode the base or foundation of", partOfSpeech: "verb", example: "Constant criticism can undermine confidence." },
  { word: "underscore", definition: "To emphasize", partOfSpeech: "verb", example: "The incident underscores the need for reform." },
  { word: "unequivocal", definition: "Leaving no doubt; unambiguous", partOfSpeech: "adjective", example: "Her answer was an unequivocal yes." },
  { word: "unprecedented", definition: "Never done or known before", partOfSpeech: "adjective", example: "The pandemic caused unprecedented disruption." },
  { word: "unscrupulous", definition: "Having no moral principles", partOfSpeech: "adjective", example: "The unscrupulous dealer cheated customers." },
  { word: "untenable", definition: "Not able to be maintained or defended", partOfSpeech: "adjective", example: "His position became untenable after the scandal." },
  { word: "urbane", definition: "Suave, courteous, and refined in manner", partOfSpeech: "adjective", example: "The urbane diplomat charmed everyone he met." },
  { word: "usurp", definition: "To take a position of power illegally or by force", partOfSpeech: "verb", example: "The general attempted to usurp the throne." },
  { word: "vacillate", definition: "To waver between different opinions or actions", partOfSpeech: "verb", example: "She vacillated between the two job offers." },
  { word: "vacuous", definition: "Having or showing a lack of thought or intelligence", partOfSpeech: "adjective", example: "The vacuous celebrity had nothing meaningful to say." },
  { word: "vehement", definition: "Showing strong feeling; forceful or passionate", partOfSpeech: "adjective", example: "She made a vehement denial of the accusations." },
  { word: "venerate", definition: "To regard with great respect", partOfSpeech: "verb", example: "Many cultures venerate their ancestors." },
  { word: "veracious", definition: "Speaking or representing the truth", partOfSpeech: "adjective", example: "The witness gave a veracious account of events." },
  { word: "verbose", definition: "Using or expressed in more words than needed", partOfSpeech: "adjective", example: "His verbose writing style bored readers." },
  { word: "vestige", definition: "A trace of something that no longer exists", partOfSpeech: "noun", example: "The ruins are a vestige of ancient civilization." },
  { word: "vex", definition: "To make someone feel annoyed or frustrated", partOfSpeech: "verb", example: "The constant delays vexed the passengers." },
  { word: "viable", definition: "Capable of working successfully", partOfSpeech: "adjective", example: "The committee reviewed all viable options." },
  { word: "vicarious", definition: "Experienced through imagined participation in another's experience", partOfSpeech: "adjective", example: "She lived vicariously through her children's adventures." },
  { word: "vigilant", definition: "Keeping careful watch for danger or difficulties", partOfSpeech: "adjective", example: "Security guards remained vigilant throughout the night." },
  { word: "vilify", definition: "To speak or write about in an abusively disparaging manner", partOfSpeech: "verb", example: "The tabloids vilified the celebrity unfairly." },
  { word: "vindicate", definition: "To clear someone of blame or suspicion", partOfSpeech: "verb", example: "The new evidence vindicated the accused." },
  { word: "virulent", definition: "Extremely severe or harmful; bitterly hostile", partOfSpeech: "adjective", example: "The virulent strain of flu spread rapidly." },
  { word: "visceral", definition: "Relating to deep inward feelings", partOfSpeech: "adjective", example: "She had a visceral reaction to the shocking news." },
  { word: "vitriolic", definition: "Filled with bitter criticism or malice", partOfSpeech: "adjective", example: "The vitriolic review destroyed the play's reputation." },
  { word: "vociferous", definition: "Expressing opinions loudly and forcefully", partOfSpeech: "adjective", example: "The vociferous protesters blocked traffic." },
  { word: "volatile", definition: "Liable to change rapidly and unpredictably", partOfSpeech: "adjective", example: "The stock market has been volatile lately." },
  { word: "voracious", definition: "Having a very eager approach to an activity", partOfSpeech: "adjective", example: "She was a voracious reader who devoured books." },
  { word: "wanton", definition: "Deliberate and unprovoked", partOfSpeech: "adjective", example: "The wanton destruction shocked the community." },
  { word: "wary", definition: "Feeling or showing caution about possible dangers", partOfSpeech: "adjective", example: "Investors remain wary of the market." },
  { word: "whimsical", definition: "Playfully quaint or fanciful", partOfSpeech: "adjective", example: "The whimsical decorations delighted children." },
  { word: "wistful", definition: "Having a feeling of vague or regretful longing", partOfSpeech: "adjective", example: "She had a wistful look remembering her childhood." },
  { word: "zealous", definition: "Having or showing great energy or enthusiasm", partOfSpeech: "adjective", example: "The zealous volunteer worked tirelessly for the cause." },
  { word: "zenith", definition: "The time at which something is most powerful or successful", partOfSpeech: "noun", example: "The empire reached its zenith in the 16th century." },
  { word: "zephyr", definition: "A soft gentle breeze", partOfSpeech: "noun", example: "A cool zephyr brought relief from the heat." }
];

